name = "RiboSwitch_Julia"
uuid = "8e0e3d00-1e00-4ca8-a362-429a00ac6c4b"
authors = ["JacopoBoccato <jacopo.boccato@gmail.com>"]
version = "0.1.0"

[deps]
AdvRBMs = "5c8d321f-d88f-4112-b4bc-67901fc2de0a"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"
SequenceLogos = "7a3f67ce-6eeb-4904-9da4-2cbd106a5944"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
AdvRBMs = "2.1.0"
CSV = "0.10.15"
CUDA = "5.9.6"
DataFrames = "1.8.1"
Distributed = "1.11.0"
JLD2 = "0.6.3"
LinearAlgebra = "1.11.0"
MLUtils = "0.4.8"
Measures = "0.3.3"
Optim = "2.0.0"
Optimisers = "0.4.7"
Plots = "1.41.4"
Printf = "1.11.0"
Random = "1.11.0"
RestrictedBoltzmannMachines = "5.1.1"
SequenceLogos = "0.2.1"
Statistics = "1.11.1"
StatsBase = "0.34.9"
XLSX = "0.10.4"
